### ISSUE TITLE
Problem with docker-py API

### ISSUE THREAD

**Issue by tofgarion** [UCL-INGI/INGInious#97] opened 2016-03-23 12:49 UTC
Hello,

I am trying to use INGInious on CentOS 7 and I have some issues with docker, particularly the Python API docker-py. INIGInious has been installed via pip.

If I install docker via normal CentOS repository and docker-py is installed automatically when installing INGInious via pip, then the client API of docker-py is too new for docker (21 instead of 20) and I cannot connect.

I have then used the repos provided by docker (https://yum.dockerproject.org/) and installed docker-engine. I can create the test course (with no errors provided by docker-py), but when I try to submit a solution in the C# Hello World task, I have the following error message:

agent - WARNING - Cannot start container! mem_limit has been moved to host_config in API version 1.19

It seems to be again a problem with the client API, see simple_agent.py file. Do you have some hints on how to solve the problem?

Thanks in advance and best regards,

Christophe

**Comment by layus** [comment] 2016-03-23 13:41
I can confirm I had the same bug. I think I fixed it once by hacking the source of INGinious, and now by using a different docker release. (Also, I am using INGInious at commit e019a0e28c442b4201ec4a0be2a816c4ab639683, which is not an official release.)

It seems to me that the issue is linked to the custom fork of docker-py used by INGInious. It is too old to support new versions of docker, and INGInious does not work with recent docker-py projects because of api changes.

The bottom of this issue is that Docker does not support clients to be more recent than the server, so the simplest solution is to install more recent docker versions.

@GuillaumeDerval, could you look into this and maybe update your https://github.com/GuillaumeDerval/docker-py project ? Or submit your changes upstream ?
Matching the docker api versions between Docker server, client and docker-py is already tedious, but having a separate fork makes it nearly impossible.

**Comment by GuillaumeDerval** [comment] 2016-03-23 13:51
94d0281848655160b9c730dc80eac22eeb4485d9 (and the 4-5 commits after) has updated INGInious to the latest version of Docker. 

Do you use the version of INGInious from pip (pip install inginious)? If you do so, maybe you should try with the latest dev version:

pip install --upgrade git+https://github.com/UCL-INGI/INGInious.git

Please, tell me if it solves your problem. (it should :D)

**Comment by tofgarion** [comment] 2016-03-23 15:28
I have installed INGInious the latest version of INGInious this morning, so the currently installed version is 0.3a2.dev0 on my machine.

I was not precise in my first report: the bug also appears when trying the Hello World task with Python in the test lecture (seems rather logical as it is not attached to a particular language).

I have upgraded ly INGInious install, but the bug is still here.

Best,

Christophe

**Comment by ohss** [comment] 2016-03-23 16:12
Hi,

I've had the same issue. I installed INGInious on AWS for testing purposes using this script: [https://manageacloud.com/api/cm/configuration/inginious_web_app_1344/centos/manageacloud-production-script.sh](https://manageacloud.com/api/cm/configuration/inginious_web_app_1344/centos/manageacloud-production-script.sh)

Everything seems to work, but submitting a task fails:

`stderr: Cannot start container! mem_limit has been moved to host_config in API version 1.19`

Docker version is 1.10.3, build 20f81dd and docker-py version is 1.7.2

Thanks a lot in advance!

-Otso

**Comment by tanguy-perennou** [comment] 2016-03-25 17:55
Hi there,

I may have found a quick and dirty fix for the issue Christophe raised, with the following configuration:
- CentOS 7
- docker-engine 1.10.3 with API version 1.22
- docker-py 1.7.2
- INGInious 0.3a2.dev0

Seems that just commenting out line 512 in `inginious/backend/agent/simple_agent.py` does the trick: I managed to run the C# Hello World task after restarting `inginious-webapp`.

Best regards,
-- Tanguy

**Comment by ohss** [comment] 2016-03-26 19:41
Thanks Tanguy, that solved the issue for now!

**Comment by GuillaumeDerval** [comment] 2016-03-26 19:58
Thanks @tanguy-perennou !

Your fix has been committed in 07d111c0a3045c7cc4e464d4adb8aa28b75a6948 .

**Closed by GuillaumeDerval** 2016-03-26 19:58 UTC
