### ISSUE TITLE
'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by ThaSami** [UCL-INGI/INGInious#495] opened 2020-01-16 13:05 UTC
This error shows when running CPP container on centos 7 or on Centos 8 
'NoneType' object has no attribute 'items'

However this error is not shown when running Python 3 containers.

i have rebuilt the images many times. no success. 
inginious is latest 0.6

**Comment by GuillaumeDerval** [comment] 2020-01-16 13:23
Do you have a full stack trace?

@Drumor is currently working on the images to make sure Docker hub have the right versions for everything. Maybe the problem will be solved once it's done, mainly if it's a collision between versions.

**Comment by ThaSami** [comment] 2020-01-16 13:35
`Jan 16 15:33:26 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: 2020-01-16 15:33:26,952 - inginious.backend - INFO - Sending job b'\x00Q_\x00|' 192ce90c-a5eb-4401-8d23-5be7441cde75 to agent b'\x>
Jan 16 15:33:26 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: 2020-01-16 15:33:26,953 - inginious.agent.docker - INFO - Received request for jobid (b'\x00Q_\x00|', '192ce90c-a5eb-4401-8d23-5be>
Jan 16 15:33:26 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: 2020-01-16 15:33:26,953 - inginious.agent.docker - INFO - Received request for jobid (b'\x00Q_\x00|', '192ce90c-a5eb-4401-8d23-5be>
Jan 16 15:33:27 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: 2020-01-16 15:33:27,333 - inginious.agent.docker - WARNING - Container cc03793db60631b92f305b7706562952fdd16855a4dca0614236eeb56fc>
Jan 16 15:33:27 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: 2020-01-16 15:33:27,333 - inginious.agent.docker - ERROR - Cannot get back output of container cc03793db60631b92f305b7706562952fdd>
Jan 16 15:33:27 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: Traceback (most recent call last):
Jan 16 15:33:27 desktop-jgmkif7.ju.edu.jo lighttpd[31720]:   File "/usr/local/lib/python3.6/site-packages/inginious/agent/docker_agent/__init__.py", line 574, in handle_job_closing
Jan 16 15:33:27 desktop-jgmkif7.ju.edu.jo lighttpd[31720]:     for key, item in return_value.items():
Jan 16 15:33:27 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: AttributeError: 'NoneType' object has no attribute 'items'
`

**Comment by ThaSami** [comment] 2020-01-16 13:35
> Jan 16 15:33:26 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: 2020-01-16 15:33:26,952 - inginious.backend - INFO - Sending job b'\x00Q_\x00|' 192ce90c-a5eb-4401-8d23-5be7441cde75 to agent b'\x>
Jan 16 15:33:26 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: 2020-01-16 15:33:26,953 - inginious.agent.docker - INFO - Received request for jobid (b'\x00Q_\x00|', '192ce90c-a5eb-4401-8d23-5be>
Jan 16 15:33:26 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: 2020-01-16 15:33:26,953 - inginious.agent.docker - INFO - Received request for jobid (b'\x00Q_\x00|', '192ce90c-a5eb-4401-8d23-5be>
Jan 16 15:33:27 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: 2020-01-16 15:33:27,333 - inginious.agent.docker - WARNING - Container cc03793db60631b92f305b7706562952fdd16855a4dca0614236eeb56fc>
Jan 16 15:33:27 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: 2020-01-16 15:33:27,333 - inginious.agent.docker - ERROR - Cannot get back output of container cc03793db60631b92f305b7706562952fdd>
Jan 16 15:33:27 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: Traceback (most recent call last):
Jan 16 15:33:27 desktop-jgmkif7.ju.edu.jo lighttpd[31720]:   File "/usr/local/lib/python3.6/site-packages/inginious/agent/docker_agent/__init__.py", line 574, in handle_job_closing
Jan 16 15:33:27 desktop-jgmkif7.ju.edu.jo lighttpd[31720]:     for key, item in return_value.items():
Jan 16 15:33:27 desktop-jgmkif7.ju.edu.jo lighttpd[31720]: AttributeError: 'NoneType' object has no attribute 'items'

**Comment by ThaSami** [comment] 2020-01-16 13:37
Problem solved by rebuilding the image by installing only gcc-c++ and gcc
```
# DOCKER-VERSION 1.1.0

FROM ingi/inginious-c-base

LABEL org.inginious.grading.name="cpp"
LABEL org.inginious.grading.agent_version=2

RUN yum install -y gcc-c++ gcc
```

**Comment by GuillaumeDerval** [comment] 2020-01-16 13:37
What was your dockerfile before?

**Comment by ThaSami** [comment] 2020-01-16 13:38
this is my old dockerfile
however it was working fine on UBUNTU server a month ago but not on Centos 7 or 8

`# DOCKER-VERSION 1.1.0

#inherit from the base container, which have all the needed script to launch tasks
FROM    ingi/inginious-c-base
LABEL org.inginious.grading.name="cpp"

# Add gcc
RUN     yum install -y gcc gcc-c++ gdb cpp make cmake valgrind binutils libstdc++ clang clang-analyzer clang-devel llvm automake check check-devel CUnit CUnit-devel zlib-devel openssl-devel time jansson-devel graphviz graphviz-devel cppcheck git python3 python3-pip && \
        pip3 install GitPython && \
        yum clean all`

**Comment by GuillaumeDerval** [comment] 2020-01-16 13:40
You are trying to reinstall python
`python3 python3-pip`
It's probably what is causing the problem.

**Comment by ThaSami** [comment] 2020-01-16 13:57
removing python3-pip will cause
/bin/sh: pip3: command not found

anw yum should have no problem of reinstalling python.
so probably something else is causing the problem
i tried to debug it with webdav / lti ssh 
it crashes even before i can debug it

**Comment by GuillaumeDerval** [comment] 2020-01-16 13:59
Any INGInious container has python/pip. IIRC it's `pip` rather than `pip3`?

**Comment by ThaSami** [comment] 2020-01-16 14:30
no idea.
however i don't see the point of putting GitPython in the cpp image.

**Comment by anthonygego** [comment] 2021-09-28 12:31
I'll close this. Feel free to re-open it if the issue is still relevant.

**Closed by anthonygego** 2021-09-28 12:31 UTC
