### ISSUE TITLE
webserver configuration

### ISSUE THREAD

**Issue by ThaSami** [UCL-INGI/INGInious#489] opened 2019-12-22 14:09 UTC
I couldn't get the lighttpd webserver configuration working on CentOs 8 following the guide in documentations !
is there any extra steps i need to do in order to get it working ?
anyone could list the lighttpd.conf ?

**Comment by GuillaumeDerval** [comment] 2020-01-28 07:20
Hey @ThaSami , sorry we could not help you in a timely manner.
Sadly I don't use lighttpd locally and I think @anthonygego does not anymore on our instances, but it should work with the one on the doc. If it does not, then it needs to be fixed!

Did you find the cause of your problem?

**Comment by ThaSami** [comment] 2020-01-29 20:31
@GuillaumeDerval  
yes i figured out the problem. after some tinkering.
1- the path of installation was differ from the one provided in the documentation. 
why? because i have installed Ingi with --user flag on PIP. 

2- the lighttpd.conf file need a lot of configurations beyond the documentation. ( much of googling would solve this ) 
i am myself not a system administrator yet i still learn. 
could you please tell me why you don't use lighttpd ? is there anything better ? 
we are about to handle 300 and more students in 3 weeks with 32gb of ram, and intelxeon 24cores. and also 1TB of ssd.
what would you recommend ?

**Comment by GuillaumeDerval** [comment] 2020-02-03 12:51
> we are about to handle 300 and more students in 3 weeks with 32gb of ram, and intelxeon 24cores. and also 1TB of ssd

I think that should work, even in a busy context (such as an exam, when you have ALL your students submitting at the same time). If you are more in a "submit-at-your-own-pace" context (student work at home, mostly) then you probably less than that.

(without guarantees obviously, you should test ;-))

**Comment by anthonygego** [comment] 2021-09-28 12:31
I'll close this as it is a duplicate of #628

**Closed by anthonygego** 2021-09-28 12:31 UTC
