### ISSUE TITLE
Run student does not handle BrokenPipeError

### ISSUE THREAD

**Issue by tdba** [UCL-INGI/INGInious#284] opened 2018-01-31 09:40 UTC
Everything in the title

Dealt with it this way:

```
try:
            resproc = subprocess.Popen(shlex.split(py_cmd), universal_newlines=True, stderr=f, stdout=subprocess.PIPE)
            resproc.communicate()
            resultat = resproc.returncode
except (IOError, BrokenPipeError):
            resultat = 252

```

**Comment by GuillaumeDerval** [comment] 2018-01-31 11:24
`run_student` does not use `stdout=subprocess.PIPE`, nor writes to anything else than the socket opened with the `_run_student_intern` in the student container.

Various processes can receive `SIGPIPE`s while running `run_student`. However, most of these possibilities are not plausible or are expected behavior.

- `run_student` can receive a `SIGPIPE` BEFORE the interruptions are handled in the code. That means that the SIGPIPE is received during the various send made between lines 54 and 79, when `run_student` talks with the Agent to start the new container, then with `_run_student_intern` to transfer the fds. This definitely a bug, and should be handled with a nice System.exit(254) if we catch it. We must indeed check that this is the cause of the bug you see, or if it's a different one. https://github.com/UCL-INGI/INGInious/blob/c072022fadf0b8f8bdcc98680ed09a63f40e67c1/base-containers/base/bin/run_student#L54-L79

- `run_student` can receive a `SIGPIPE` AFTER the interruptions are handled in the code. This would not create an exception but rather a very slow infinite loop. See #285. Probably not the cause of your bug, but still a bug.

- `_run_student_intern` can receive a `SIGPIPE` when writing to its *own* output pipes (stdout/stderr). I can't see a case where this would happen, but since Docker is a complicated application, I would not be completely surprised. In that case, I also don't see how the exception could be shown to us. So I don't believe it's the problem, and I don't think we should do something about it. It is expected in that case that it crashes.

- `_run_student_intern` can NOT receive a `SIGPIPE` if the fds sent by `run_student` are closed, since it does not write directly to it. 

- The underlying command started by `_run_student_intern` can receive a SIGPIPE if the fds of `run_student` are closed, which is excepted bahviour

- As a last possibility, the implementation of subprocessing could send a BrokenPipeError, but I really don't see why it would do that.

The first point needs investigation. The second one, #285, needs a fix when we have time, as it's not at all critical (an infinite loop would be `SIGKILL`ed by the wall timeout)

**Comment by GuillaumeDerval** [comment] 2018-01-31 11:27
Note that the first bullet (`run_student` that cannot write to the Agent or `_run_student_intern` before the interruption are handled) can only happen if there is another bug:
- agent is not responsive
- `_run_student_intern` crashed at startup

We should look into that too.

**Comment by GuillaumeDerval** [comment] 2020-11-19 23:30
After a careful re-reading an analyzing everything again, I don't believe this can actually in the current version of the code. Let me know if I'm wrong, with a way to reproduce the problem ideally :-)

In the meantime, let's close this.

**Closed by GuillaumeDerval** 2020-11-19 23:30 UTC
Labels: Agent, Bug
